CHANNEL_LIST = {'Волинська': 'Uvaga_tryvoha_Volyn',
                'Вінницька':'sirena_vinnytsia',
                'Чернівецька':'sirena_chernivtsi',
                'Дніпровська':'sirena_dp',
                'Донецька':'Z_Donbas',
                'Кропивницька':'surenakrop',
                'Сумська':'surenasumy',
                'Житомирська':'sirena_zhytomyr',
                'Закарпаття':'sirena_zakarpatiia',
                'Київська': 'sirena_kyiv',
                'Львівська':'signal_lviv',
                'Миколаївська':'sirena_mykolaiv',
                'Одеська':'odessa_sirena',
                'Івано-Франківська':'signal_if',
                'Полтавська':'sirena_poltava',
                'Рівненська':'sirena_rivne',
                'Тернопільська':'sirena_ternopil',
                'Харьківська' :'sirena_kharkiv',
                'Херсонська'  : 'sirena_kherson',
                'Хмельницька' :'truvoganmr',
                'Черкаська'   :'sirena_cherkasy',
                'Чернігівська':'sirena_chernihiv',
                'Запорізька'  :'sirena_zaporizhzhia',
                }